### ISSUE TITLE
Similarity with the original app

### ISSUE THREAD

**Issue by JohnFai91** [headuck/GoOutWithDuck#2]
Thanks for being on F-Droid, overall it's a very well-made app but the UI can still have umprovemnets to make it more similar with the real one. The bottom navigation bar should be taller and with 3 items: "Home", "Inbox", and "Settings". I suggest the "notifications" part should connect to a new fragment to inbox and activities are implemented onto the main page and then add a new "inbox" fragment while replacing "History" with "Settings". As far as I am concerned, you would like to make a preference page for users to configure for their own style. Many thanks!

**Comment by headuck** [comment]
Thank you for your comments. Emulation of the official app is not a goal of this app. Some elements of UI are similar just for easy pick up by users. There was no legal requirement for mandatory use of the official app when this project starts, and further versions will make the UI less similar to avoid legal issues. The inbox and setting fragments will be added in future.
